### ISSUE TITLE
msgq fetches all messages 1000 times

### ISSUE THREAD

**Issue by Taywee** [jwoehr/ublu#21]
[MessageQueue notes that getMessages fetches in blocks of 1000 messages](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_72/rzahh/javadoc/com/ibm/as400/access/MessageQueue.html#getMessages()), but it looks like that's an implementation detail, and not an invitation to call getMessages over and over again:

```
> put -to @queue /qsys.lib/qsysopr.msgq
> calljava -to @mq -new com.ibm.as400.access.MessageQueue -arg @as400 -arg @queue
> calljava -- @mq -method getLength
41668
> calljava -to @enum -- @mq -method getMessages
> num -to @i -long 0
> tuple -true @keepgoing
> \\ ${ Iterate all messages in enum, incrementing @i for each }$
> WHILE @keepgoing $[ calljava -to message -- @enum -method nextElement
calljava -to @keepgoing -- @enum -method hasMoreElements
eval -to @i + @i 1 ]$
> put @i
41668
> WHILE @keepgoing $[ calljava -to message -- @enum -method nextElement
calljava -to @keepgoing -- @enum -method hasMoreElements
eval -to @i + @i 1 ]$
> put @i
83336
```

Here in MsgQ, though, it will apparently iterate the message queue 1000 times for every message that is in the queue, because getMessages always returns an enumerable to the beginning of the queue: https://github.com/jwoehr/ublu/blob/master/src/ublu/command/CmdMsgQ.java#L398-L404
It should be fixable just by getting rid of the outer `for` loop and iterating the enumeration.

For one of these hosts, we have 40k messages, which should be manageable, but it ends up getting an OutOfMemoryError even when given a Java heap size of 2G:

```
> msgq -as400 @as400 -to @messages -all /qsys.lib/qsysopr.msgq
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.ibm.as400.access.DataStreamCompression.decompressRLE(DataStreamCompression.java:446)
	at com.ibm.as400.access.RCCallProgramReplyDataStream.getParameterList(RCCallProgramReplyDataStream.java:55)
	at com.ibm.as400.access.RemoteCommandImplRemote.runProgramOffThread(RemoteCommandImplRemote.java:581)
	at com.ibm.as400.access.RemoteCommandImplRemote.runProgram(RemoteCommandImplRemote.java:532)
	at com.ibm.as400.access.ProgramCall.run(ProgramCall.java:785)
	at com.ibm.as400.access.ListUtilities.retrieveListEntries(ListUtilities.java:302)
	at com.ibm.as400.access.MessageQueue.getMessages(MessageQueue.java:513)
	at com.ibm.as400.access.QueuedMessageEnumeration.nextElement(QueuedMessageEnumeration.java:72)
	at ublu.command.CmdMsgQ.readMessageQueue(CmdMsgQ.java:424)
	at ublu.command.CmdMsgQ.msgq(CmdMsgQ.java:288)
	at ublu.command.CmdMsgQ.cmd(CmdMsgQ.java:454)
	at ublu.util.Interpreter.loop(Interpreter.java:1222)
	at ublu.util.Interpreter.interpret(Interpreter.java:1422)
	at ublu.Ublu.runMainInterpreter(Ublu.java:337)
	at ublu.Ublu.niam(Ublu.java:397)
	at ublu.Ublu.main(Ublu.java:366)
```

Right now, I'm working around this by doing it all with calljava manually.

**Comment by Taywee** [comment]
My current workaround:

```
    LOCAL @mq
    calljava -to @mq -new com.ibm.as400.access.MessageQueue -arg @as400 -arg @msgqueue
    calljava -- @mq -method load

    LOCAL @enum
    calljava -to @enum -- @mq -method getMessages

    LOCAL @keepgoing
    calljava -to @keepgoing -- @enum -method hasMoreElements

    WHILE @keepgoing $[
        LOCAL @message
        calljava -to @message -- @enum -method nextElement
        calljava -to @keepgoing -- @enum -method hasMoreElements
```

**Comment by jwoehr** [comment]
Made change. Try it out and let me know. See my email for special build instructions.

**Comment by jwoehr** [comment]
Fixed.
